<h1>Hands-on Activity</h1>

<?php
    $table = array(
        "header"=>array(
            "Firstname",
            "Middlename",
            "Lastname",
            "Section",
            "Course",
            "Yearlevel"
        ),
        "body"=>[
            array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        array(
            "Firstname"=>"Firstname",
            "Middlename"=>"Middlename",
            "Lastname"=>"Lastname",
            "Section"=>"Section",1
            "Course"=>"Course",
            "Yearlevel"=>"Yearlevel"
        ),
        
    ],
    )
?>